server:
  port: 8000
spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://192.168.80.129:32007/demo?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: w1324
    driver-class-name: com.mysql.cj.jdbc.Driver
#配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
# 配置SQL日志输出
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl